service: default
runtime: nodejs16
env: standard
instance_class: F1

automatic_scaling:
    max_instances: 1
    min_instances: 0
    max_idle_instances: 1
    min_idle_instances: 0

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
