service: default
runtime: nodejs16
env: standard
instance_class: F1

automatic_scaling:
  max_instances: 2
  min_instances: 1
  max_idle_instances: 1
  min_idle_instances: 0

inbound_services:
  - warmup

handlers:
- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: /data
  static_dir: public/data

- url: /img
  static_dir: public/img

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

error_handlers:
 - file: error.html
