service: default
runtime: nodejs16
env: standard
instance_class: B1

manual_scaling:
  instances: 1

handlers:
- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: /data
  static_dir: public/data

- url: /img
  static_dir: public/img

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
