indexes:

- kind: Photo
  properties:
  - name: flocks
  - name: submittedAt
    direction: desc

- kind: Illustration
  properties:
  - name: species
  - name: full

- kind: MemberPet
  properties:
  - name: member
  - name: hatchedAt
    direction: desc

- kind: MemberFlock
  properties:
  - name: member
  - name: displayOrder 
